---

# Attribution @ktvGIT for build logic

image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

build_job:
  stage: build
  script:
    - echo 'Building'

test_unit_job:
  stage: test
  script:
    - echo 'Testing 1'

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: "branch/$CI_COMMIT_REF_NAME"
    url: "http://${CI_ENVIRONMENT_SLUG}.${GITLAB_SERVER_HOST}"
  only:
    - branches
  except: []

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: 'http://dev.example.com'

staging:
  stage: stage
  when: manual
  only:
    - '/^\d+\.\d+\.\d+/'
  script:
    - echo 'Deploy'
  environment:
    name: beta
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - '/^\d+\.\d+\.\d+/'
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  GIT_SUBMODULE_STRATEGY: recursive
  APP_DIR: 'reddit-module/'

before_script:
  - cp gitlab-ci/simpletest.rb "$APP_DIR"
  - echo "gem 'rack-test'" >> "$APP_DIR/Gemfile"
  - pushd "$APP_DIR"
  - bundle install

---

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

# TEST WORKAROUND - cd reddit
