---

# Attribution to @ktvGIT for build logic
# Attribution to Tsvetan Nikolov for build and deployment logic
# https://blog.itelekt.com/build-deploy-run-docker-image-with-gitlab/

default:
  image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

build_job:
  stage: build
  image: docker:20.10
  services:
    - docker:20.10-dind
  before_script:
    - docker login
      -u "$CI_DOCKER_REGISTRY_USER"
      -p "$CI_DOCKER_REGISTRY_TOKEN"
      docker.io
  script:
    - docker build
      --pull -f ./gitlab-ci/Dockerfile -t "$IMAGE_SPEC" .
    - docker push "$IMAGE_SPEC"

test_unit_job:
  stage: test
  script:
    - echo 'Testing 1'

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

branch review:
  stage: review
  image: docker:20.10
  services:
    - docker:20.10-dind
  before_script:
    - mkdir -p ~/.ssh/
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config
    - chown 600 "$CI_DOCKER_HOST_ID_RSA_FILE"
    - eval $(ssh-agent -s)
    - ssh-add "$CI_DOCKER_HOST_ID_RSA_FILE"
    - docker login
      -u "$CI_DOCKER_REGISTRY_USER"
      -p "$CI_DOCKER_REGISTRY_TOKEN"
      docker.io
  # TODO Should parametrize outer port to avoid conflicts
  script:
    - export DOCKER_HOST="$CI_DOCKER_HOST_URI"
    - docker pull "$IMAGE_SPEC"
    - docker stop "$CONTAINER_NAME" || true
    - docker rm "$CONTAINER_NAME" || true
    - docker run
      --name "$CONTAINER_NAME" --restart always
      -d -p 9292:9292 "$IMAGE_SPEC"
  environment:
    name: "branch/$CI_COMMIT_REF_NAME"
    url: "http://${CI_ENVIRONMENT_SLUG}.${GITLAB_SERVER_HOST}"
  variables:
    CONTAINER_NAME: reddit
  only:
    - branches
  except: []

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: 'http://dev.example.com'

staging:
  stage: stage
  when: manual
  only:
    - '/^\d+\.\d+\.\d+/'
  script:
    - echo 'Deploy'
  environment:
    name: beta
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - '/^\d+\.\d+\.\d+/'
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  GIT_SUBMODULE_STRATEGY: recursive
  APP_DIR: 'reddit-module/'
  IMAGE_SPEC: 'bergentroll/gitlab-ci-reddit:latest'

...
---

test_unit_job:
  stage: test
  services:
    - mongo:latest
  before_script:
    - cp gitlab-ci/simpletest.rb "$APP_DIR"
    - echo "gem 'rack-test'" >> "$APP_DIR/Gemfile"
    - pushd "$APP_DIR"
    - bundle install
  script:
    - ruby simpletest.rb

...

# TEST WORKAROUND - cd reddit
