---

version: '3'

x-defaults: &defaults
  restart: always

services:
  fluentd:
    <<: *defaults
    image: ${USERNAME}/fluentd
    build: ../logging/fluentd/
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    <<: *defaults
    image: elasticsearch:7.4.0
    environment:
      - ELASTIC_CLUSTER=false
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    <<: *defaults
    image: kibana:7.4.0
    ports:
      - "5601:5601"
