---

version: '3.3'

services:
  post_db:
    image: mongo:3.2
    restart: always
    volumes:
      - post_db:/data/db
    networks:
      - backend
  ui:
    build:
      context: ../src/ui/
      dockerfile: Dockerfile.0
    image: '${USERNAME}/ui:${APP_TAG}'
    restart: always
    ports:
      - '${APP_PORT}:9292/tcp'
    networks:
      - frontend
  post:
    build: ./../src/post-py/
    image: '${USERNAME}/post:${APP_TAG}'
    restart: always
    networks:
      - backend
      - frontend
  comment:
    build:
      context: ../src/comment/
      dockerfile: Dockerfile.0
    image: '${USERNAME}/comment:${APP_TAG}'
    restart: always
    networks:
      - backend
      - frontend
  prometheus:
    image: '${USERNAME}/prometheus:latest'
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:  # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'  # Задаем время хранения метрик в 1 день
    networks:
      - backend
      - frontend

volumes:
  post_db: {}
  prometheus_data: {}

networks:
  frontend:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  backend:
    ipam:
      config:
        - subnet: 10.0.2.0/24
