---

- name: Install k8s
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - debug:
        var: '{{ item }}'
      tags: debug
      with_items:
        - inventory_hostname
        - ansible_host
    - name: Install basic requirements
      package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - docker.io
        state: present
        update_cache: true
    - name: Tune dockerd
      notify: Restart Docker
      copy:
        src: files/dockerd-daemon.json
        dest: /etc/docker/daemon.json
        mode: '0644'
    - name: Add Google GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: Add k8s repo
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes
    - name: Install k8s packages
      package:
        name:
          - kubelet
          - kubeadm
        state: present
  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted

- name: Setup master node
  hosts: masters
  become: true
  gather_facts: false
  tasks:
    - name: Install kubectl packages
      package:
        name: kubectl
        state: present
    - name: Reset k8s setup
      shell: kubeadm reset --force
    - name: Init control-plane node
      shell: >
        kubeadm init
        --apiserver-cert-extra-sans={{ ansible_host }}
        --apiserver-advertise-address=0.0.0.0
        --control-plane-endpoint={{ ansible_host }}
        --pod-network-cidr=10.244.0.0/16
    - name: Get command to join nodes  # Atribution to yar2dev
      shell: kubeadm token create --print-join-command
      register: kuber_registration_token
    - name: Set command to join nodes
      set_fact:
        kubeadm_join_command: "{{ kuber_registration_token.stdout }}"
    - name: Place the Calico manifest
      notify: Apply Calico manifest
      copy:
        src: files/calico.yaml
        dest: /root/calico.yaml
        mode: '0644'
  handlers:
    - name: Apply Calico manifest
      shell: >
        kubectl --kubeconfig=/etc/kubernetes/admin.conf
        apply --filename /root/calico.yaml

- name: Connect nodes
  hosts: nodes
  become: true
  gather_facts: false
  tasks:
    - name: Reset k8s setup
      shell: kubeadm reset --force
    - name: Join to cluster  # Attribution to yar2dev
      shell: "{{ hostvars[groups['masters'][0]]['kubeadm_join_command'] }}"
