---

services:
  ui:
    command:
      - 'puma'
      - '--debug'
      - '--workers'
      - '${PUMA_WORKERS}'
    volumes:
      - './ui/:${APP_HOME}/'
  post:
    volumes:
      - './post-py/:${APP_HOME}/'
  comment:
    command:
      - 'puma'
      - '--debug'
      - '--workers'
      - '${PUMA_WORKERS}'
    volumes:
      - './comment/:${APP_HOME}/'
