---

version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit
  ui:
    build:
      context: ./ui/
      dockerfile: Dockerfile.0
    image: ${USERNAME}/ui:latest
    ports:
      - 9292:9292/tcp
    networks:
      - reddit
  post:
    build: ./post-py/
    image: ${USERNAME}/post:latest
    networks:
      - reddit
  comment:
    build:
      context: ./comment/
      dockerfile: Dockerfile.0
    image: ${USERNAME}/comment:latest
    networks:
      - reddit

volumes:
  post_db:

networks:
  reddit:
