---

version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - backend
  ui:
    build:
      context: ./ui/
      dockerfile: Dockerfile.0
    image: ${USERNAME}/ui:latest
    ports:
      - 9292:9292/tcp
    networks:
      - frontend
  post:
    build: ./post-py/
    image: ${USERNAME}/post:latest
    networks:
      - backend
      - frontend
  comment:
    build:
      context: ./comment/
      dockerfile: Dockerfile.0
    image: ${USERNAME}/comment:latest
    networks:
      - backend
      - frontend

volumes:
  post_db:

networks:
  frontend:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  backend:
    ipam:
      config:
        - subnet: 10.0.2.0/24
